# Schema for the configuration files of the Parse.ly Tag module.

parsely_tag.settings:
  type: config_object
  label: Parse.ly Tag Settings
  mapping:
    site_id:
      type: string
      label: The Site ID provided by Parse.ly.
    default_enable:
      type: boolean
      label: Default enabled state for triggering the Parse.ly tag.
    default_type:
      type: string
      label: Default setting for the "@type" property.
    default_headline:
      type: string
      label: Default setting for the "headline" property.
    default_url:
      type: string
      label: Default setting for the "url" property.
    default_thumbnail_url:
      type: string
      label: Default setting for the "thumbnailUrl" property.
    default_date_created:
      type: string
      label: Default setting for the "dateCreated" property.
    default_article_section:
      type: string
      label: Default setting for the "articleSection" property.
    default_creator:
      type: string
      label: Default setting for the "creator" property.
    default_keywords:
      type: string
      label: Default setting for the "keywords" property.

node.type.*.third_party.parsely_tag:
  type: mapping
  label: Parse.ly Tag Node Type Settings
  mapping:
    enable:
      type: boolean
      label: Whether to use a Parse.ly tag for this node type.
    type:
      type: string
      label: Node type property.
    headline:
      type: string
      label: Node headline property.
    url:
      type: string
      label: Node URL.
    thumbnail_url:
      type: string
      label: URL for a thumbnail representing the node.
    date_created:
      type: string
      label: Node created date property.
    article_section:
      type: string
      label: Node section (category) property.
    creator:
      type: string
      label: Node creator(s) property.
    keywords:
      type: string
      label: Node keywords property.
